### PR TITLE
[WIP] add dynamic type and weight support

### PR DESCRIPTION
**Pull request by Alex293**
Hey this is WIP, to gather feedback.

This add support for weights in addition to bold and enable dynamic type. 
Tests won't passe due to dynamic type changing the font size, I'm wondering if this should be toggle-able and a separate property of the MarkupStyleFont.

AppKit part is not updated yet.

### CODE REVIEW

**Comment by zhgchgli0718** [comment]
I will review ASAP, thanks for your contribution.

**Comment by CodeHYY** [comment]
We are facing an issue with this "weight support." The proposed solution above is acceptable. Please handle promptly. Thank you. @zhgchgli0718

**Comment by zhgchgli0718** [comment]
I have adjusted the tests and the AppKit. If there are no issues, we can proceed with merging and releasing it. Thank you for your contribution.

**Comment by CodeHYY** [comment]
@zhgchgli0718 
CocoaPods Specs cannot find version **1.12.0**， Please submit this version.
https://github.com/CocoaPods/Specs/tree/master/Specs/2/5/b/ZMarkupParser

**Comment by zhgchgli0718** [comment]
> @zhgchgli0718 CocoaPods Specs cannot find version **1.12.0**， Please submit this version. https://github.com/CocoaPods/Specs/tree/master/Specs/2/5/b/ZMarkupParser

done, https://github.com/CocoaPods/Specs/tree/master/Specs/2/5/b/ZMarkupParser/1.12.0

**Pull request merged**
