### PR TITLE
Store the color directly instead of the RGBA values

### PR DESCRIPTION
**Pull request by mbarringer**
Currently, `MarkupStyleColor` stores the RGBA values directly, which doesn't work with dynamic colors, so toggling from white mode to dark mode leaves the text dark and illegible.

This PR changes `MarkupStyleColor` to store a provided `UIColor` or `NSColor` directly, rather than converting it to RGBA.

### CODE REVIEW

**Comment by zhgchgli0718** [comment]
Could you also take a look at the unit tests that are failing and fix them?, thank you.

**Comment by mbarringer** [comment]
The related unit tests are fixed to compare the colors directly, but the snapshot tests fail even against HEAD, so I don't think that has anything to do with my changes.

**Comment by zhgchgli0718** [comment]
I'll check it later, thank you.

**Comment by zhgchgli0718** [comment]
will release ASAP

**Pull request merged**
